name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run action
      id: run_action
      uses: ./
      with: 
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        summary: 'Summary'
        title: 'Title'
        text: 'Text'
        theme-color: '28a745'
        sections: |
          - images:
              - image: 'https://github.blog/wp-content/uploads/2019/08/DL-V2-LinkedIn_FB.png?fit=1200%2C630'
                title: 'Github Actions'
          - activityTitle: "Section title"
            activitySubtitle: "Section subtitle"
            activityImage: "https://github.com/luisghz.png"
            facts:
              - name: 'Fact 1'
                value: 'Value 1'
              - name: 'Fact 2'
                value: 'Value 2'
        potential-action: |
            - "@type": "OpenUri"
              name: "Open Executed Action"
              targets:
                - os: "default"
                  uri: "https://docs.microsoft.com/outlook/actionable-messages"