name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run action
      id: run_action
      uses: ./
      with: 
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        summary: 'Summary'
        title: 'Title'
        theme-color: '28a745'
        sections: |
          - activityTitle: "Section title"
            activitySubtitle: "Section subtitle"
            activityImage: "https://github.com/luisghz.png"
            facts:
              - name: 'Fact 1'
                value: 'Value 1'
              - name: 'Fact 2'
                value: 'Value 2'