name: "test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run action
      id: run_action
      uses: ./
      with: 
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        summary: 'Summary'
        title: 'Title'
        print-json: true
        # text: '![Alt text for the image](https://pbs.twimg.com/media/C8NK1XGUIAA-CJK.jpg)'
        text: 'Text'
        sections: |
          - activityTitle: "Section title by {gh:actor}"
            activitySubtitle: "Section subtitle. Click [here]({gh:actor-url}) or {gh:actor-link} to go to user profile. Or click on {gh:run-number-link} to go to executed workflow."
            activityImage: "{gh:avatar-url}"
            facts:
              - name: 'Fact 1'
                value: 'Value 1'
              - name: 'Fact 2'
                value: 'Value 2'
        potential-action: |
            - "@type": "OpenUri"
              name: "Open Executed Action"
              targets:
                - os: "default"
                  uri: "https://docs.microsoft.com/outlook/actionable-messages"

    - name: Send Error message to MS Teams if job fails
      uses: ./
      with:
        print-json: true
        webhook_url: ${{ secrets.WEBHOOK_URI }}
        title: Something was wrong with ${{ github.workflow }}
        theme-color: 'Error'
        sections: |
          - activityTitle: "Something was wrong with ${{ github.workflow }} executed by {gh:actor}"
            activitySubtitle: "${{ github.workflow }} {gh:run-number-link}"
            activityImage: "{gh:avatar-url}"
            facts:
              - name: "Enviroment:"
                value: "${{ env.INPUT_ENVIROMENT }}"
              - name: "Repository"
                value: "[${{ github.repository }}](https://github.com/${{ github.repository }})"
              - name: "Branch ref:"
                value: "${{ github.ref }}"

    # - name: run action with false print-json
    #   uses: ./
    #   with: 
    #     webhook_url: ${{ secrets.WEBHOOK_URL }}
    #     summary: 'Summary'
    #     title: 'Title with false print-json'
    #     print-json: false
    #     # text: '![Alt text for the image](https://pbs.twimg.com/media/C8NK1XGUIAA-CJK.jpg)'
    #     text: 'Text'
    #     sections: |
    #       - activityTitle: "Section title by {gh:actor}"
    #         activitySubtitle: "Section subtitle. Click [here]({gh:actor-url}) to go to user profile. Or click on {gh:run-number-link} to go to executed workflow."
    #         activityImage: "{gh:avatar-url}"